### PR TITLE
Fix test_sqlitecachedb_upgrade.py

### PR DESCRIPTION
**Pull request by whirm**

### CODE REVIEW

**Comment by LipuFei** [comment]
@whirm This is fine, I fixed them in #6

**Comment by LipuFei** [comment]
@whirm I will close this one. The only unit test needs to be fixed now is the database upgrade.

**Comment by whirm** [comment]
Then cherry pick the 7a5348d

Could you tell me which ones are pending?

**Comment by LipuFei** [comment]
@whirm I have changed everything to use `SqliteCacheDb` so there is no need to cherry pick it. The only thing pending is fixing `test_sqlitecachedb_upgrade.py`. We can do it tomorrow when we test my branch together.

**Comment by whirm** [comment]
That's what the pull request was for. Check the diff again.

**Comment by LipuFei** [comment]
It will not work because the old database is way too old and our upgrade script doesn't support it. What we need to do with `test_sqlitecachedb_upgrade.py` is to make at least two new tests:
1. one to test upgrade from a very old version, which should fail because we don't support it.
2. another to test upgrade from 5.9.x or higher, and this should succeed.

**Comment by whirm** [comment]
Ok, I've checked and the database is still at V1 after initialising, we should get an exception there.

**Pull request closed without merging**
